name: Run all time scripts

on:
  workflow_dispatch:

jobs:
  time_all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Call 'time' job for each test file in 'examples'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

        run: |
          for file in "./examples/*/*.mrsh"; do
            echo "Calling 'time' job with 'test' input: $file"
            curl -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/json" \
              "https://api.github.com/repos/$GITHUB_REPOSITORY/dispatches" \
              -d '{"event_type": "time", "client_payload": {"test": "$file"}}'
          done